### ISSUE TITLE
Add support for self-hosted Jitsi installations

### ISSUE THREAD

**Issue by saghul** [ONLYOFFICE/plugin-jitsi#4]
👋  Very cool to see this plugin!

A small feature-request: since Jitsi Meet can be self-hosted, just like ONLYOFFICE, I think it would be nice to have the possibility to configure the domain (defaulting to meet.jit.si is a good idea) for those who are also self-hosting Jitsi Meet.

**Comment by DenisDeeSign** [comment]
Hi @saghul,
thank you for this idea. I created an issue 55869 in our internal issue tracker.

**Comment by saghul** [comment]
🚀
